### ISSUE TITLE
Integrate full yt-dlp support from micah686/YoutubeDLSharp/tree/ytdlp/master

### ISSUE THREAD

**Issue by micah686** [Bluegrams/YoutubeDLSharp#18]
So, on my fork [ytdlp/master](https://github.com/micah686/YoutubeDLSharp/tree/ytdlp/master), I have basically implemented all of the updated features of yt-dlp. 

However, as I did this, there were `Options` that got removed because they were no longer applicable, as well as some methods that got rearranged/moved around. This fork also uses .net 6, and removes Newtonsoft.Json in favor of the built in (.net 6) `System.Text.Json`.   

Would you like to proceed with using the new `YtDlpSharpLib`? Or would you rather have me work on maintaining it as a seperate project/nuget package?

**Comment by alxnull** [comment]
Hey @micah686,

In general, I'm very happy to integrate updates and changes from your side into this project. I'm trying to gradually switch this project fully to yt-dlp and already have integrated many of the yt-dlp updates in the latest commits. You're very welcome to contribute further changes of yt-dlp now or in the future. (It might be a bit difficult to sync our changes at the moment though, as we've both done updates independently.)

However, there are some changes of your version that I'm hesistant to merge back into this repo at the moment:
- I'd prefer not to change the name of the package and namespace, keeping `YoutubeDLSharp` for consistency.
- while adding .NET 6 as a target is possible, I don't want to drop support for classic .NET Framework (yet)
- because of the former, switching away from `Newtonsoft.Json` is not an option at the moment

If you would like to go into a different direction with your fork, you're of course free to maintain it independently of this project. I'd be happy to collaborate on a single solution for everyone though.

**Comment by micah686** [comment]
Understood, and I agree with your reasons on why you don't want the changes that I've added merged in yet. I did end up creating a separate repo for yt-dlp specifically (https://github.com/micah686/YtDlpSharpLib), if you want to take a look at it to see what I've changed on then. I'd be willing to collaborate at a later time to bring our changes together into one project, just let me know when you want to do that.
