### ISSUE TITLE
Does it work on Linux?

### ISSUE THREAD

**Issue by D2O84** [Bluegrams/YoutubeDLSharp#23]
Hi
Is YoutubeDLSharp suppose to work on Linux?, it works fine on windows but fails on Linux I have this error
`An error occurred trying to start process 'yt-dlp.exe' with working directory '/home/...'. No such file or directory`

I'm using 
<PackageReference Include="YoutubeDLSharp" Version="1.0.0-beta2" />

And
`await YoutubeDL.DownloadYtDlpBinary();
await YoutubeDL.DownloadFFmpegBinary();`

Thank you

**Comment by alxnull** [comment]
Hey @D2O84,

In principle, it should also work on Linux (although it's currently not actively tested on platforms other than Windows).
From your error message, it seems that the path to the yt-dlp binary is not set correctly to work on Linux, where the downloaded binary should be named just `yt-dlp` instead of `yt-dlp.exe`.

You can configure this as follows:
```csharp
var ytlp = new YoutubeDL()
{
    YoutubeDLPath = "yt-dlp"
};
```

**Comment by D2O84** [comment]
That worked, 

`YoutubeDLPath = OperatingSystem.IsLinux() ? "yt-dlp" : "yt-dlp.exe",
FFmpegPath = OperatingSystem.IsLinux() ? "ffmpeg" : "ffmpeg.exe"`

Thank you
